name: budget_app
description: "A Flutter version of the JarBudget application."
publish_to: "none" # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0 # For state management
  shared_preferences: ^2.0.0 # For local storage
  uuid: ^4.0.0 # For generating unique IDs
  intl: ^0.19.0 # For date formatting
  flutter_colorpicker: ^1.0.0 # For color selection in settings (optional)
  lucide_icons: ^0.257.0 # For using Lucide icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
