name: Setup and build
description: Setup flutter and build the flutter web project

inputs:
  base-href:
    description: The base href for the web build
    required: false
    default: "/"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Build web project
      run: flutter build web --release --base-href "${{ inputs.base-href }}"
      shell: bash
